# E-commerce Fraud Modeling

Step 1: Load the Processed Fraud Dataset

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/fraud_processed.csv")

df.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,age,ip_address,class,time_since_signup,hour_of_day,...,country_United States,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Viet Nam,country_Virgin Islands (U.S.),country_Yemen,country_Zambia,country_Zimbabwe
0,247547,2015-06-28 03:00:34,2015-08-09 03:57:29,0.549607,KIXYSVCHIPQBR,-0.363124,16778864,0,-0.413800,3,...,False,False,False,False,False,False,False,False,False,False
1,220737,2015-01-28 14:21:11,2015-02-11 20:28:28,-1.197335,PKYOWQKWGJNJI,0.101168,16842045,0,-1.180852,20,...,False,False,False,False,False,False,False,False,False,False
2,390400,2015-03-19 20:49:09,2015-04-11 23:41:23,0.385831,LVCSXLISZHVUO,-0.479197,16843656,0,-0.936126,23,...,False,False,False,False,False,False,False,False,False,False
3,69592,2015-02-24 06:11:57,2015-05-23 16:40:14,0.986342,UHAUHNXXUADJE,-0.363124,16938732,0,0.867086,16,...,False,False,False,False,False,False,False,False,False,False
4,174987,2015-07-07 12:58:11,2015-11-03 04:04:30,0.767974,XPGPMOHIDRMGE,0.449387,16971984,0,1.700633,4,...,False,False,False,False,False,False,False,False,False,False

In [2]:
df.shape

(129146, 202)

In [3]:
df.columns

Index(['user_id', 'signup_time', 'purchase_time', 'purchase_value',
       'device_id', 'age', 'ip_address', 'class', 'time_since_signup',
       'hour_of_day',
       ...
       'country_United States', 'country_Uruguay', 'country_Uzbekistan',
       'country_Vanuatu', 'country_Venezuela', 'country_Viet Nam',
       'country_Virgin Islands (U.S.)', 'country_Yemen', 'country_Zambia',
       'country_Zimbabwe'],
      dtype='str', length=202)

# Step 2: Separate Features and Target

In [5]:
X = df.drop("class", axis=1)
y = df["class"]

print(X.shape)
print(y.shape)

(129146, 201)
(129146,)

# Step 3: Train-Test Split

In [22]:
X = df.drop(
    columns=[
        "class",
        "signup_time",
        "purchase_time",
        "device_id"
    ]
)

y = df["class"]

In [23]:
print(X.shape)
print(y.shape)

(129146, 198)
(129146,)

In [24]:
X = X.select_dtypes(exclude=["object"])

In [25]:
print(X.select_dtypes(include=["object"]).columns.tolist())

[]

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Step 4: Apply SMOTE

In [27]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print("Before:")
print(y_train.value_counts())

print("\nAfter:")
print(y_train_smote.value_counts())

Before:
class
0    93502
1     9814
Name: count, dtype: int64

After:
class
0    93502
1    93502
Name: count, dtype: int64

# STEP 5 — Logistic Regression (Baseline Model)

In [28]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr.fit(X_train_smote, y_train_smote)

LogisticRegression(max_iter=1000, random_state=42)

# STEP 6 — Predictions

In [29]:
y_pred_lr = lr.predict(X_test)
y_prob_lr = lr.predict_proba(X_test)[:, 1]

# STEP 7 — Evaluation (VERY IMPORTANT)

Import metrics

In [30]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    average_precision_score,
    f1_score
)

In [31]:
print("F1 Score:", f1_score(y_test, y_pred_lr))

F1 Score: 0.16689847009735745

In [32]:
print("AUC-PR:", average_precision_score(y_test, y_prob_lr))

AUC-PR: 0.09583477778878663

In [33]:
print(confusion_matrix(y_test, y_pred_lr))

[[10673 12703]
 [ 1074  1380]]

In [34]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.91      0.46      0.61     23376
           1       0.10      0.56      0.17      2454

    accuracy                           0.47     25830
   macro avg       0.50      0.51      0.39     25830
weighted avg       0.83      0.47      0.57     25830

# STEP 8 — Random Forest Model

In [35]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)

rf.fit(X_train_smote, y_train_smote)

RandomForestClassifier(max_depth=10, random_state=42)

# STEP 9 — Random Forest Predictions

In [36]:
y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:, 1]

# STEP 10 — Random Forest Evaluation

In [37]:
print("F1 Score:", f1_score(y_test, y_pred_rf))
print("AUC-PR:", average_precision_score(y_test, y_prob_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

F1 Score: 0.6699834162520729
AUC-PR: 0.681993608045396
[[23023   353]
 [ 1040  1414]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     23376
           1       0.80      0.58      0.67      2454

    accuracy                           0.95     25830
   macro avg       0.88      0.78      0.82     25830
weighted avg       0.94      0.95      0.94     25830

# STEP 11 — Cross Validation (IMPORTANT REQUIREMENT)

In [38]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    rf,
    X,
    y,
    cv=cv,
    scoring="f1"
)

print(scores)
print("Mean F1:", scores.mean())
print("Std:", scores.std())

[0.69259457 0.70894737 0.70177296 0.70295983 0.70774092]
Mean F1: 0.7028031274328962
Std: 0.005786777966431634

# STEP 12 — Compare Models

In [39]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "F1 Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_rf)
    ],
    "AUC-PR": [
        average_precision_score(y_test, y_prob_lr),
        average_precision_score(y_test, y_prob_rf)
    ]
})

results

                 Model  F1 Score    AUC-PR
0  Logistic Regression  0.166898  0.095835
1        Random Forest  0.669983  0.681994

# STEP 13 — Save Best Model

In [40]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(rf, "../models/random_forest_fraud.pkl")

['../models/random_forest_fraud.pkl']

In [41]:
os.listdir("../models")

['random_forest_fraud.pkl']

Logistic Regression was used as an interpretable baseline model. Random Forest achieved higher F1-score and AUC-PR, indicating better detection of fraudulent transactions. Therefore, Random Forest was selected as the best-performing model for the fraud dataset.

# Credit Card Fraud Modeling

# Step 1: Load Credit Card Dataset

In [43]:
import pandas as pd

credit_df = pd.read_csv("../data/raw/creditcard.csv")

credit_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [44]:
credit_df.shape

(284807, 31)

In [45]:
credit_df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='str')

# Step 2: Separate Features and Target

In [46]:
X_cc = credit_df.drop("Class", axis=1)
y_cc = credit_df["Class"]

print(X_cc.shape)
print(y_cc.shape)

(284807, 30)
(284807,)

# Step 3: Train-Test Split

In [47]:
from sklearn.model_selection import train_test_split

X_train_cc, X_test_cc, y_train_cc, y_test_cc = train_test_split(
    X_cc,
    y_cc,
    test_size=0.2,
    random_state=42,
    stratify=y_cc
)

# Step 4: Check Class Imbalance

In [48]:
print(y_train_cc.value_counts())

Class
0    227451
1       394
Name: count, dtype: int64

# Step 5: Apply SMOTE

In [49]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_cc_smote, y_train_cc_smote = smote.fit_resample(
    X_train_cc,
    y_train_cc
)

In [50]:
print("Before:")
print(y_train_cc.value_counts())

print("\nAfter:")
print(y_train_cc_smote.value_counts())

Before:
Class
0    227451
1       394
Name: count, dtype: int64

After:
Class
0    227451
1    227451
Name: count, dtype: int64

# Step 6: Logistic Regression

In [51]:
from sklearn.linear_model import LogisticRegression

lr_cc = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_cc.fit(
    X_train_cc_smote,
    y_train_cc_smote
)

c:\Users\admin\Desktop\10-academy\fraud-detection\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000, random_state=42)

In [52]:
y_pred_lr_cc = lr_cc.predict(X_test_cc)

print("Model trained successfully")

Model trained successfully

# Step 7: Logistic Regression Predictions

In [53]:
y_pred_lr_cc = lr_cc.predict(X_test_cc)

y_prob_lr_cc = lr_cc.predict_proba(X_test_cc)[:, 1]

# Step 8: Evaluate Logistic Regression

In [55]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    average_precision_score,
    f1_score
)

In [56]:
print("F1 Score:")
print(f1_score(y_test_cc, y_pred_lr_cc))

F1 Score:
0.20828402366863905

In [57]:
print("AUC-PR:")
print(average_precision_score(
    y_test_cc,
    y_prob_lr_cc
))

AUC-PR:
0.7318953330210467

In [59]:
print("Confusion Matrix:")
print(confusion_matrix(
    y_test_cc,
    y_pred_lr_cc
))

Confusion Matrix:
[[56205   659]
 [   10    88]]

In [60]:
print("Classification Report:")
print(classification_report(
    y_test_cc,
    y_pred_lr_cc
))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     56864
           1       0.12      0.90      0.21        98

    accuracy                           0.99     56962
   macro avg       0.56      0.94      0.60     56962
weighted avg       1.00      0.99      0.99     56962

# Step 9: Random Forest

In [61]:
from sklearn.ensemble import RandomForestClassifier

rf_cc = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42
)

rf_cc.fit(
    X_train_cc_smote,
    y_train_cc_smote
)

RandomForestClassifier(max_depth=10, random_state=42)

# Step 10: Random Forest Predictions

In [62]:
y_pred_rf_cc = rf_cc.predict(X_test_cc)

y_prob_rf_cc = rf_cc.predict_proba(X_test_cc)[:, 1]

# Step 11: Evaluate Random Forest

In [63]:
print("F1 Score:")
print(f1_score(y_test_cc, y_pred_rf_cc))

print("AUC-PR:")
print(average_precision_score(
    y_test_cc,
    y_prob_rf_cc
))

print(confusion_matrix(
    y_test_cc,
    y_pred_rf_cc
))

print(classification_report(
    y_test_cc,
    y_pred_rf_cc
))

F1 Score:
0.6566037735849056
AUC-PR:
0.8160189399136879
[[56784    80]
 [   11    87]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.52      0.89      0.66        98

    accuracy                           1.00     56962
   macro avg       0.76      0.94      0.83     56962
weighted avg       1.00      1.00      1.00     56962

# Step 12: Cross Validation

In [64]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores_cc = cross_val_score(
    rf_cc,
    X_cc,
    y_cc,
    cv=cv,
    scoring="f1"
)

print(scores_cc)
print("Mean F1:", scores_cc.mean())
print("Std:", scores_cc.std())

[0.83060109 0.8700565  0.87777778 0.85227273 0.84444444]
Mean F1: 0.8550305079132532
Std: 0.0170861642944895

# Step 13: Compare Models

In [66]:
results_cc = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    "F1 Score": [
        f1_score(y_test_cc, y_pred_lr_cc),
        f1_score(y_test_cc, y_pred_rf_cc)
    ],
    "AUC-PR": [
        average_precision_score(
            y_test_cc,
            y_prob_lr_cc
        ),
        average_precision_score(
            y_test_cc,
            y_prob_rf_cc
        )
    ]
})

results_cc

                 Model  F1 Score    AUC-PR
0  Logistic Regression  0.208284  0.731895
1        Random Forest  0.656604  0.816019

# Step 14: Save Best Model

In [67]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(
    rf_cc,
    "../models/random_forest_creditcard.pkl"
)

['../models/random_forest_creditcard.pkl']

In [68]:
os.listdir("../models")

['random_forest_creditcard.pkl', 'random_forest_fraud.pkl']

# conclusion for the Credit Card section

Logistic Regression was used as a baseline model for credit card fraud detection. Random Forest achieved superior F1-score and AUC-PR, demonstrating better performance on the highly imbalanced dataset. Therefore, Random Forest was selected as the final model for credit card fraud detection.

# Model Selection Summary

For both datasets, Logistic Regression was used as a baseline model due to its interpretability.

Random Forest achieved higher F1-Score and AUC-PR, indicating better performance in identifying fraudulent transactions while maintaining a balance between precision and recall.

Therefore, Random Forest was selected as the final model for both the e-commerce fraud dataset and the credit card fraud dataset.